/* Low-latency Web Audio with original local music and sound effects. */
(() => {
'use strict';
class AudioSystem {
 constructor(){this.ctx=null;this.buffers=new Map();this.loading=new Map();this.music=null;this.track=null;this.wantTrack=null;this.paused=true;this.last={};this.voices=0;try{this.settings=JSON.parse(localStorage.getItem('zs7-audio'))||{music:.45,effects:.75}}catch{this.settings={music:.45,effects:.75}}}
 async unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);this.fx=this.ctx.createGain();this.fx.gain.value=this.settings.effects;this.fx.connect(this.master);this.master.gain.value=this.paused?0:1;for(const name of ['pistol','smg','shotgun','dmr','burst','hit','hurt','grenade','throw','ricochet','pickup','boost','alarm','whoosh','victory','loss','boss-attack'])this.buffer('sfx-'+name+'.mp3');}if(this.ctx.state!=='running')await this.ctx.resume();if(this.wantTrack&&!this.paused)this.playMusic(this.wantTrack);}catch{}}
 async buffer(file){if(this.buffers.has(file))return this.buffers.get(file);if(this.loading.has(file))return this.loading.get(file);const task=fetch('./'+file).then(r=>{if(!r.ok)throw Error(file);return r.arrayBuffer()}).then(b=>this.ctx.decodeAudioData(b)).then(b=>{this.buffers.set(file,b);return b}).catch(()=>null).finally(()=>this.loading.delete(file));this.loading.set(file,task);return task;}
 async playMusic(track){this.wantTrack=track;if(!this.ctx||this.paused||this.track===track)return;this.track=track;const buffer=await this.buffer('music-'+track+'.mp3');if(!buffer||this.wantTrack!==track||this.paused){if(this.track===track)this.track=null;return;}const now=this.ctx.currentTime;if(this.music){const old=this.music;old.gain.gain.cancelScheduledValues(now);old.gain.gain.setValueAtTime(old.gain.gain.value,now);old.gain.gain.linearRampToValueAtTime(0,now+.4);try{old.source.stop(now+.45)}catch{}}const source=this.ctx.createBufferSource(),gain=this.ctx.createGain();source.buffer=buffer;source.loop=track!=='entrance';source.connect(gain);gain.connect(this.master);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(this.settings.music,now+.4);source.start();source.onended=()=>{source.disconnect();gain.disconnect();if(this.track===track&&!source.loop){this.track=null;if(this.wantTrack&&this.wantTrack!==track)this.playMusic(this.wantTrack)}};this.music={source,gain};}
 async sfx(name,volume=1){if(!this.ctx||this.paused||this.settings.effects===0||this.voices>18)return;const time=performance.now(),minGap={hit:50,ricochet:80,'boss-attack':140}[name]||25;if(time-(this.last[name]||0)<minGap)return;this.last[name]=time;const buffer=await this.buffer('sfx-'+name+'.mp3');if(!buffer||this.paused)return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=buffer;s.playbackRate.value=['hit','pistol','smg'].includes(name)?.96+Math.random()*.08:1;g.gain.value=volume;s.connect(g);g.connect(this.fx);this.voices++;s.onended=()=>{this.voices--;s.disconnect();g.disconnect()};s.start();}
 set(kind,value){this.settings[kind]=Math.max(0,Math.min(1,Number(value)));try{localStorage.setItem('zs7-audio',JSON.stringify(this.settings))}catch{}if(this.ctx){if(kind==='effects')this.fx.gain.setTargetAtTime(this.settings.effects,this.ctx.currentTime,.03);else this.music?.gain.gain.setTargetAtTime(this.settings.music,this.ctx.currentTime,.05)}}
 pause(){this.paused=true;if(this.ctx)this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.035)}
 resume(){this.paused=false;if(this.ctx)this.master.gain.setTargetAtTime(1,this.ctx.currentTime,.025);this.unlock()}
}
window.ZSAudio=AudioSystem;
})();
