(() => {
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const {BOSSES,SKINS,MAPS}=ZSData,audio=new ZSAudio(),scores=new ZSScores(),renderer=new ZSRenderer($('gameCanvas'));
let ready=false,paused=true,landscape=false,admin=false,run=null,pendingName='',sceneKey='',panel='',lastTime=0,accumulator=0,saveClock=0,toastTimer,installPrompt,lastFit='';
let storyStep=0,storyTimer=null,storyReplay=false;
let touchAxis=0,touchFire=false,stickId=null,fireId=null,keys=new Set(),padGrenade=false;
const game=new ZSEngine.Game({onEvent:event});
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3100)}
function clearInput(){touchAxis=0;touchFire=false;stickId=null;fireId=null;keys.clear();game.resetInput();$('stickKnob').style.transform='translateX(0)';$('fireButton').classList.remove('pressed');$('joystick').setAttribute('aria-valuenow','0')}
function save(){if(run&&game.active&&!game.over)write('zs7-run',{engine:game.snapshot(),run:{id:run.id,name:run.name,ticket:run.ticket}});else if(game.over)try{localStorage.removeItem('zs7-run')}catch{}}
function pause(){paused=true;clearInput();audio.pause();save()}
function resume(){if(!game.active||game.over||landscape)return;paused=false;accumulator=0;lastTime=performance.now();audio.resume();audio.playMusic(game.scene?.kind==='arrival'?'entrance':game.boss?.bossId==='discoman'?'disco':game.boss?'boss':'main')}
function closePanel(){panel='';$('overlay').hidden=true;clearInput();if(game.active&&!game.over)resume();else showStart();$('menuButton').focus({preventScroll:true})}
function showPanel(kind,title,html,{closable=true,start=false}={}){clearTimeout(storyTimer);pause();panel=kind;const box=$('overlay');box.hidden=false;box.innerHTML=(title?`<div class="panel-head"><h2>${esc(title)}</h2>${closable?'<button data-action="close" aria-label="Close panel">×</button>':''}</div>`:'')+`<div class="panel-content ${start?'start-panel':''}">${html}</div>`}
function showStart(){const name=read('zs7-name',''),saved=read('zs7-run',null);showPanel('start','',`<div class="start-heroes" aria-label="Joey Rob versus Dr Mantis"><img src="./player-victory.webp" alt="Joey Rob"><b>VS</b><img src="./boss-drmantis-stage1.webp" alt="Dr Mantis"></div><h1>HOLD THE LINE.</h1><p>One Joey Rob. Seven bosses. No backing down.<br>Move left/right. Hold FIRE. Make every kill count.</p><form id="startForm"><label class="name-field">YOUR NAME ON THE SCOREBOARD<input name="username" id="username" value="${esc(name)}" maxlength="24" minlength="2" autocomplete="off" autocorrect="off" inputmode="text" autocapitalize="none" spellcheck="false" placeholder="Enter your player name" required></label><button class="primary-action" id="startButton" ${ready?'':'disabled'}>${ready?'PLAY ZOMBIE SMASH':'LOADING THE HORDE…'}</button></form>${saved?.engine?.active?`<button class="secondary-action" data-action="continue">CONTINUE ${esc(saved.run?.name)} · WAVE ${saved.engine.wave}</button>`:''}<div class="loading-line" id="loadingLine">${ready?'NO LOGIN · ALL SKINS UNLOCKED':'Loading game artwork…'}</div>`,{start:true,closable:false})}
function menu(){if(panel==='menu'){closePanel();return}showPanel('menu','GAME MENU',`${game.active?'<button class="primary-action" data-action="close">RESUME GAME</button>':'<button class="primary-action" data-action="home">PLAY ZOMBIE SMASH</button>'}<button class="menu-action" data-action="skins">CONSOLE SKINS <small>All unlocked →</small></button><button class="menu-action" data-action="board">HIGH SCORES <small>The leaderboard →</small></button><button class="menu-action" data-action="sound">MUSIC & SOUND <small>Set your mix →</small></button><button class="menu-action" data-action="story">THE STORY <small>Replay the comic →</small></button><button class="menu-action" data-action="help">HOW TO PLAY <small>Controls & boosts →</small></button><button class="menu-action" data-action="install">INSTALL GAME <small>Play from Home Screen →</small></button>${game.active?'<button class="menu-action" data-action="restart">NEW RUN <small>Choose a player name →</small></button>':''}<button class="menu-action" data-action="admin">${admin?'ADMIN CONTROLS':'ADMIN CODE'} <small>${admin?'Bosses & cheats →':'Unlock tools →'}</small></button><p class="menu-note">${run?'Playing as '+esc(run.name):'Zombie Smash'} · v7.6<br>Portrait arcade · Joey Rob vs Dr Mantis</p>`)}
function start(name,skipIntro=false){storyReplay=false;name=name.trim();if(!scores.validName(name)){toast('Use 2–24 letters, numbers, spaces, dots, dashes or underscores.');return}write('zs7-name',name);pendingName=name;if(!skipIntro&&!read('zs7-story-seen',false)){showStory(name,0);return}beginRun(name)}
const storySlides=[
 {art:'story-mantis.webp',title:'THE DOCTOR WILL SEE YOU NOW',copy:'Dr Mantis is on the hunt for human prostates. His ambition? Become the KING OF PROCTOLOGY.'},
 {art:'story-army.webp',title:'YOUR MATES. HIS ARMY.',copy:"He has brainwashed JoeyRob’s former comrades and raised an army of zombies. Every familiar face is now a boss standing in your way."},
 {art:'story-joey.webp',title:'ONE LAST LINE OF DEFENCE',copy:'JoeyRob has one job: free his mates, stop the harvest, and hold the line. Move left and right. Fire up the street. Make it count.'}
];
function showStory(name,index=0){pendingName=name;storyStep=index;const slide=storySlides[index];showPanel('story',`THE HUNT · ${index+1} / 3`,`<img class="story-art" src="./${slide.art}" alt="${esc(slide.title)}"><div class="story-copy"><h3>${slide.title}</h3><p>${slide.copy}</p></div><div class="story-dots" aria-label="Scene ${index+1} of 3">${storySlides.map((_,i)=>`<i class="${i===index?'current':''}"></i>`).join('')}</div><button class="primary-action" data-action="${index===2?'begin-run':'story-next'}">${index===2?(storyReplay?'RESUME GAME':'HOLD THE LINE'):'NEXT PANEL →'}</button><button class="secondary-action" data-action="begin-run">${storyReplay?'BACK TO GAME':'SKIP INTRO & PLAY'}</button>`,{closable:false});if(index<2&&!matchMedia('(prefers-reduced-motion:reduce)').matches)storyTimer=setTimeout(()=>{if(panel==='story')showStory(pendingName,index+1)},7500);}

function beginRun(name){clearTimeout(storyTimer);write('zs7-story-seen',true);run={id:crypto.randomUUID(),name,ticket:null,submitted:false};const thisRun=run;thisRun.ticketPromise=scores.begin(name).then(ticket=>{thisRun.ticket=ticket;if(run===thisRun)save();return ticket});game.reset();$('overlay').hidden=true;panel='';sceneKey='';game.start();resume();save()}
function applySkin(id){const skin=SKINS.find(s=>s.id===id)||SKINS[0];for(const [k,v] of Object.entries({'--skin-art':`url('./${skin.file}')`,'--accent':skin.accent,'--bleed':skin.bleed,'--fire':skin.fire||'#ef3042','--grenade':skin.grenade||'#159de8','--stick':skin.stick||'#d8a34e'}))document.body.style.setProperty(k,v);write('zs7-skin',skin.id)}
function skins(){showPanel('skins','CHOOSE YOUR CONSOLE',`<p class="menu-note">Every finish is ready to play.</p><div class="skin-options">${SKINS.map(s=>`<button class="skin-choice ${read('zs7-skin','carbon')===s.id?'selected':''}" data-skin="${s.id}" aria-pressed="${read('zs7-skin','carbon')===s.id}"><img src="./${s.file}" alt="${s.name} portrait console"><b>${s.name}</b></button>`).join('')}</div><p class="menu-note">Your arena, enemies and controls keep exactly the same proportions in every skin.</p><button class="secondary-action" data-action="menu">BACK TO MENU</button>`)}
async function board(){showPanel('board','HIGH SCORES','<p class="menu-note">Loading the board…</p>');const result=await scores.board();if(panel!=='board')return;const rows=Array.isArray(result.rows)?result.rows:[];$('overlay').querySelector('.panel-content').innerHTML=`<p class="menu-note">${result.online?'Online leaderboard':'Saved leaderboard · offline'}<br>Original records are preserved. New runs use your player name.</p>${rows.map((r,i)=>`<div class="board-row"><b class="rank">${i+1}</b><span>${esc(r.username||r.name||r.gamertag)}${r.legacy?'<small>ORIGINAL RECORD</small>':''}</span><b class="points">${Number(r.score||r.high_score||0).toLocaleString()}</b></div>`).join('')}<button class="secondary-action" data-action="menu">BACK TO MENU</button>`}
function sound(){showPanel('sound','MUSIC & SOUND',`<p class="menu-note">A driving arcade score, heavier boss battles, and Disco Man’s own dance floor.</p><label class="setting">MUSIC <input aria-label="Music volume" data-volume="music" type="range" min="0" max="100" value="${audio.settings.music*100}"></label><label class="setting">EFFECTS <input aria-label="Effects volume" data-volume="effects" type="range" min="0" max="100" value="${audio.settings.effects*100}"></label><button class="secondary-action" data-action="preview-sound">PREVIEW MIX</button><button class="secondary-action" data-action="menu">BACK TO MENU</button>`)}
function help(){showPanel('help','HOLD THE LINE',`<p class="menu-note"><strong>MOVE</strong> — slide the left joystick sideways. Joey stays on his defence line.<br><br><strong>FIRE</strong> — hold the red button. Drag and fire together.<br><br><strong>GRENADE</strong> — tap the blue centre button. The grenade travels straight up Joey's current lane — there is no auto-aim. Line yourself up first.<br><br><strong>BOOST</strong> — chain kills within 7 seconds: 10 kills = ×2, 20 = ×4, 30 = ×10. Taking damage or letting a zombie into camp breaks the chain.<br><br><strong>WATCH THE HORDE</strong> — runners warn before charging, toxic zombies fire slime, Fuse tanks can chain-react, and Bulwark shields open between pulses. DMR rounds and grenades punch through shields.<br><br><strong>BARRELS</strong> — shoot the red hazard barrels. Their blast radius is 20% of the arena width and can chain into nearby barrels.<br><br><strong>PICKUPS</strong> — drops are deliberately rarer. Special guns are stored in the four HUD slots; press the stored weapon you want when you need it. You can hold one ammo run of each gun type.<br><br><strong>BOSSES</strong> — a new boss arrives every second wave. Watch the warning before each attack. Defeat Mantis to reach infinite survival.<br><br>Keyboard: ← → or A / D · Space = fire · G = grenade · P = pause.<br>Gamepad: left stick · A / right trigger = fire · B = grenade.</p><button class="secondary-action" data-action="menu">BACK TO MENU</button>`)}
function install(){const installed=matchMedia('(display-mode:standalone)').matches||navigator.standalone;showPanel('install','TAKE THE HORDE WITH YOU',`<div class="start-heroes" aria-label="Joey Rob versus Dr Mantis"><img src="./player-victory.webp" alt="Joey Rob"><b>VS</b><img src="./boss-drmantis-stage1.webp" alt="Dr Mantis"></div><h3 style="font:900 26px Barlow;color:#ffdc8b;margin:12px 0">SEVEN BOSSES. ONE LAST STAND.</h3><p class="menu-note">Big boss reveals. Explosive weapons. Your next high score.<br>Launch straight from your Home Screen, and play offline once the game has finished downloading.</p>${installed?'<p class="menu-note">✓ You’re already playing the installed game.</p>':installPrompt?'<button class="primary-action" data-action="install-now">INSTALL ZOMBIE SMASH</button>':'<p class="menu-note"><strong>iPhone / iPad</strong><br>Open this game in Safari. Tap Share, then “Add to Home Screen”.<br><br><strong>Android</strong><br>Open your browser menu and choose “Install app” or “Add to Home screen”.</p>'}<p class="menu-note" id="offlineStatus">${read('zs7-offline-ready',false)?'Game download complete · offline play ready.':'Keep the game open while its artwork and music download.'}</p><button class="secondary-action" data-action="menu">BACK TO MENU</button>`)}
function adminPanel(){if(!admin){showPanel('admin','ADMIN CODE',`<p class="menu-note">Use your existing admin code to unlock boss selection and practice cheats.</p><form id="adminForm"><label class="name-field">ADMIN CODE<input type="password" name="code" id="adminCode" autocomplete="off" required></label><button class="primary-action">UNLOCK</button></form><p class="menu-note" id="adminStatus"></p>`);return}showPanel('admin','BOSSES & CHEATS',`<p class="menu-note">Using a cheat or boss jump makes the run practice-only. Practice scores never enter the board.</p><label class="setting">INVINCIBLE <input type="checkbox" data-cheat="invincible" ${game.invincible?'checked':''}></label><label class="setting">UNLIMITED AMMO <input type="checkbox" data-cheat="infiniteAmmo" ${game.infiniteAmmo?'checked':''}></label><button class="secondary-action" data-action="grenades">REFILL GRENADES</button><div style="display:flex;gap:5px">${Object.keys(ZSEngine.GUNS).map(g=>`<button class="secondary-action" data-gun="${g}" style="font-size:11px">${g.toUpperCase()}</button>`).join('')}</div>${BOSSES.map(b=>`<div class="boss-choice"><img src="./${b.sprites[0]}" alt=""><div><b>${b.name}</b>${Array.from({length:b.stages},(_,i)=>`<button data-boss="${b.id}" data-stage="${i+1}">FORM ${i+1}</button>`).join(' ')}</div></div>`).join('')}`)}
function practice(){if(!admin)return false;if(!run||!game.active){run={id:crypto.randomUUID(),name:read('zs7-name','Player'),ticket:null};game.reset();game.start()}game.practice=true;return true}
function results(reason){showPanel('results',game.practice?'PRACTICE COMPLETE':'RUN COMPLETE',`<div style="text-align:center"><p class="menu-note">${esc(run?.name)} · ${esc(reason)}</p><div class="score-result">${game.score.toLocaleString()}</div><div class="result-stats"><span><b>${game.wave}</b>WAVE</span><span><b>${game.kills}</b>KILLS</span><span><b>${game.bossesDown.length}</b>BOSSES</span></div><p class="menu-note" id="scoreStatus">${game.practice?'Practice run · not added to the board.':'Saving your score…'}</p><button class="primary-action" data-action="retry">ONE MORE RUN</button><button class="secondary-action" data-action="board">HIGH SCORES</button><button class="secondary-action" data-action="home">CHANGE PLAYER NAME</button></div>`,{closable:false});save();submitScore()}
async function submitScore(){if(!run||run.submitted)return;run.submitted=true;const completed=run,record={name:run.name,score:game.score,kills:game.kills,seconds:game.t,wave:game.wave,practice:game.practice};if(run.ticketPromise)await run.ticketPromise;const result=await scores.finish({...record,ticket:completed.ticket});if(run!==completed)return;const status=$('scoreStatus');if(status)status.textContent={practice:'Practice run · not added to the board.',online:'Score saved to the online leaderboard.',pending:'Saved on this device. Online upload queued for reconnection.',local:'Saved on this device. This offline run has no online ticket.',rejected:'Saved on this device. The online board could not accept this run.'}[result.status]}
function event(type,data){if(type==='music'){if(game.scene?.kind==='arrival')audio.playMusic('entrance');else audio.playMusic(data.track);return}const sounds={shot:data.gun,kill:'hit',ricochet:'ricochet',boost:'boost',breach:'hurt',clear:'pickup',hurt:'hurt',pickup:'pickup',throw:'throw',explosion:'grenade',entrance:'alarm',panel:'whoosh',mutation:'alarm',bossAttack:'boss-attack',bossDown:'victory',death:'loss'};if(sounds[type])audio.sfx(sounds[type],type==='kill'?.55:1);if(type==='fight')audio.playMusic(data.id==='discoman'?'disco':'boss');if(type==='over')results(data.reason);if(type==='wave')save()}
function cinematic(){const s=game.scene,box=$('cinematic');if(!s){box.hidden=true;sceneKey='';return}const key=[s.kind,s.bossId,s.phase,s.stage].join(':');if(sceneKey===key)return;sceneKey=key;box.hidden=false;const b=BOSSES.find(b=>b.id===s.bossId);box.className=s.kind==='down'?'scene-down':'';box.style.setProperty('--scene-color',b?.accent||'#b45139');let content='';
 if(s.kind==='arrival'&&s.phase===0)content='<div class="scene-alert">WARNING!<small>HOSTILE APPROACHING</small></div>';
 else if(s.kind==='mutation'){const reaction=s.stage===3;content=`<div class="scene-name long">${esc(b.name)}<span>FORM ${s.stage} OF ${b.stages} · ${reaction?'FINAL MUTATION':'TRANSFORMATION'}</span></div><div class="scene-figures ${reaction?'dual':''}">${reaction?'<img class="scene-art joey" src="./joey-reaction-close.webp" alt="Joey Rob reacts to the final mutation">':''}<img class="scene-art" src="./${b.sprites[s.stage-1]}" alt="${esc(b.name)} form ${s.stage}"></div><div class="scene-copy"><small>${reaction?'JOEY ROB':'THREAT EVOLVING'}</small><p>${esc(b.stageLines[s.stage-1]||b.react)}</p></div>`;}
 else if(s.kind==='arrival'&&s.phase===1)content=`<div class="scene-name">JOEY ROB<span>SOMETHING’S COMING…</span></div><div class="scene-figures"><img class="scene-art joey" src="./joey-reaction-close.webp" alt="Joey Rob reacts in shock"></div><div class="scene-copy"><small>JOEY ROB</small><p>${esc(b.announce)}</p></div>`;
 else if(b){const line=s.kind==='down'?b.finalLine:s.kind==='loss'?b.playerLoss:b.tease;content=`<div class="scene-name ${b.name.length>14?'long':''}">${s.kind==='down'?'BOSS DOWN':esc(b.name)}<span>${esc(b.title)}</span></div><div class="scene-figures"><img class="scene-art" src="./${b.sprites[(s.stage||s.startStage||1)-1]}" alt="${esc(b.name)}"></div><div class="scene-copy"><small>${esc(b.name)}</small><p>${esc(line)}</p></div>`;}
 else content='<div class="scene-alert">LINE BROKEN<small>THE HORDE GOT THROUGH</small></div>';
 box.innerHTML='<div class="scene-backdrop"></div><div class="scene-lines"></div>'+content+'<button class="scene-next" id="advanceScene">CONTINUE →</button>';box.onclick=()=>{if(!paused)game.advanceScene()};}

function hud(){const p=game.player;$('waveValue').textContent=game.wave;$('leftValue').textContent=game.boss?'BOSS':Math.max(0,game.target-game.resolved);$('scoreValue').textContent=game.score.toLocaleString();$('bestValue').textContent=scores.getBest(run?.name||read('zs7-name','')).toLocaleString();$('healthValue').textContent='♥ '.repeat(Math.max(0,p.lives)).trim()+' ♡'.repeat(Math.max(0,5-p.lives));$('healthValue').setAttribute('aria-label',p.lives+' hearts');$('gunValue').textContent=ZSEngine.GUNS[p.gun].name;$('ammoValue').textContent=!Number.isFinite(p.ammo)||game.infiniteAmmo?'∞':p.ammo;$('baseValue').textContent=game.breaches+'/10';$('grenadeValue').textContent=p.grenades;$('grenadeButton').classList.toggle('empty',p.grenades===0);$('grenadeButton').setAttribute('aria-label','Throw grenade, '+p.grenades+' remaining');$('boostText').textContent='BOOST ×'+game.multiplier;$('boostFill').style.width=Math.max(0,game.comboLeft/7*100)+'%';$('comboText').textContent=game.combo>=30?'×10 · KEEP IT GOING':((game.combo<10?10:game.combo<20?20:30)-game.combo)+' KILLS TO ×'+(game.combo<10?2:game.combo<20?4:10);for(const gun of ['smg','shotgun','dmr','burst']){const el=$('inv-'+gun);const active=p.gun===gun,ammo=active?p.ammo:(p.inventory?.[gun]||0);if(el)el.textContent=ammo||'—';const btn=document.querySelector(`[data-weapon="${gun}"]`);if(btn){btn.disabled=active||!(ammo>0);btn.classList.toggle('ready',ammo>0);btn.classList.toggle('equipped',active);btn.setAttribute('aria-label',`${active?'Equipped':'Use'} ${ZSEngine.GUNS[gun].name}, ${ammo} rounds`)}}$('mapLabel').textContent=MAPS[Math.min(6,Math.floor((game.wave-1)/2))].name;$('headerName').textContent=run?.name||'JOEY ROB VS DR MANTIS'}
function inputs(){let axis=touchAxis+(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),fire=touchFire||keys.has('Space'),grenade=false;try{const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(pad){if(Math.abs(pad.axes[0]||0)>.14)axis=pad.axes[0];if(pad.buttons[14]?.pressed)axis=-1;if(pad.buttons[15]?.pressed)axis=1;fire||=!!(pad.buttons[0]?.pressed||pad.buttons[7]?.pressed);grenade=!!pad.buttons[1]?.pressed;if(grenade&&!padGrenade)game.grenade()}}catch{}padGrenade=grenade;game.setInput(axis,fire)}
function fit(){const root=document.documentElement,focused=/INPUT|TEXTAREA/.test(document.activeElement?.tagName||''),vv=visualViewport,w=Math.max(1,root.clientWidth||innerWidth),h=Math.max(1,root.clientHeight||innerHeight),keyboard=focused&&vv&&vv.height<innerHeight*.78,newLandscape=w>h*1.04;landscape=newLandscape;$('rotateGate').hidden=!landscape;if(landscape){if(game.active&&!paused){pause();menu()}return}if(keyboard)return;const safe=getComputedStyle(document.documentElement),top=parseFloat(safe.getPropertyValue('--safe-top'))||0,bottom=parseFloat(safe.getPropertyValue('--safe-bottom'))||0,usableH=h-top-bottom;const scale=Math.min(w/375,usableH/667),key=w+'x'+h+'@'+scale.toFixed(4);if(key===lastFit)return;lastFit=key;document.documentElement.style.setProperty('--console-scale',scale);$('cabinet').style.left=(w/2)+'px';$('cabinet').style.top=(top+usableH/2)+'px';renderer.resize()}
function frame(now){fit();const dt=Math.min(.1,(now-lastTime)/1000||0);lastTime=now;if(!paused&&!landscape&&!document.hidden&&ready){inputs();accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps++<6){game.step(1/60);accumulator-=1/60}saveClock+=dt;if(saveClock>5){saveClock=0;save()}}else accumulator=0;renderer.draw(game);cinematic();hud();requestAnimationFrame(frame)}
const stick=$('joystick');function moveStick(e){if(e.pointerId!==stickId)return;const r=stick.getBoundingClientRect(),raw=(e.clientX-(r.left+r.width/2))/(r.width*.34),value=Math.max(-1,Math.min(1,raw));touchAxis=Math.abs(value)<.1?0:Math.sign(value)*(Math.abs(value)-.1)/.9;$('stickKnob').style.transform=`translateX(${value*25}px)`;stick.setAttribute('aria-valuenow',Math.round(touchAxis*100))}
stick.addEventListener('pointerdown',e=>{if(paused||!game.active||game.scene)return;e.preventDefault();stickId=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e);audio.unlock()});stick.addEventListener('pointermove',moveStick);for(const type of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(type,e=>{if(e.pointerId===stickId){stickId=null;touchAxis=0;$('stickKnob').style.transform='translateX(0)';stick.setAttribute('aria-valuenow','0')}});
$('fireButton').addEventListener('pointerdown',e=>{if(paused||!game.active||game.scene)return;e.preventDefault();fireId=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);touchFire=true;e.currentTarget.classList.add('pressed');audio.unlock();game.fire()});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('fireButton').addEventListener(type,e=>{if(e.pointerId===fireId){touchFire=false;fireId=null;e.currentTarget.classList.remove('pressed')}});
$('grenadeButton').addEventListener('pointerdown',e=>{if(paused)return;e.preventDefault();audio.unlock();game.grenade()});$('weaponRack').addEventListener('click',e=>{const b=e.target.closest('[data-weapon]');if(!b||paused)return;if(game.useStored(b.dataset.weapon)){audio.sfx('pickup');toast(ZSEngine.GUNS[b.dataset.weapon].name+' equipped')}});$('menuButton').onclick=menu;$('pauseButton').onclick=()=>{if(!game.active){showStart();return}if(paused&&panel==='menu')closePanel();else menu()};
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName))return;if(['ArrowLeft','ArrowRight','Space','KeyA','KeyD','KeyG','KeyP','Escape'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat){if(panel&&game.active)closePanel();else menu()}return}if(paused)return;keys.add(e.code);if(e.code==='Space'&&!e.repeat){audio.unlock();game.fire()}if(e.code==='KeyG'&&!e.repeat)game.grenade()});addEventListener('keyup',e=>keys.delete(e.code));
$('overlay').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...$('overlay').querySelectorAll('button:not(:disabled),input,a[href]')];if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
$('overlay').addEventListener('submit',async e=>{e.preventDefault();if(e.target.id==='startForm'){if(ready)start($('username').value)}if(e.target.id==='adminForm'){const button=e.target.querySelector('button'),code=$('adminCode').value;$('adminCode').value='';button.disabled=true;try{admin=(await scores.admin(code))===true;if(admin)adminPanel();else $('adminStatus').textContent='Code not accepted. Try again.'}catch{$('adminStatus').textContent='Could not verify the code. Check your connection.'}finally{button.disabled=false}}});
$('overlay').addEventListener('input',e=>{const kind=e.target.dataset.volume;if(kind)audio.set(kind,e.target.value/100)});$('overlay').addEventListener('change',e=>{const cheat=e.target.dataset.cheat;if(cheat&&admin&&practice()){game[cheat]=e.target.checked;save();toast('Practice mode · scores off')}});
$('overlay').addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.skin){applySkin(button.dataset.skin);skins();return}if(button.dataset.boss&&admin){practice();game.skipBoss(button.dataset.boss,Number(button.dataset.stage));sceneKey='';closePanel();save();return}if(button.dataset.gun&&admin){practice();game.equip(button.dataset.gun);toast('Weapon ready · practice mode');return}switch(button.dataset.action){case 'close':closePanel();break;case 'home':showStart();break;case 'menu':menu();break;case 'skins':skins();break;case 'board':board();break;case 'sound':sound();break;case 'help':help();break;case 'install':install();break;case 'admin':adminPanel();break;case 'restart':showPanel('restart','START A NEW RUN?',`<p class="menu-note">Your current run will end without submitting its score.</p><button class="primary-action" data-action="home">CHOOSE PLAYER & START</button><button class="secondary-action" data-action="close">KEEP PLAYING</button>`);break;case 'retry':start(run.name,true);break;case 'story':storyReplay=game.active;showStory(read('zs7-name','Player'),0);break;case 'story-next':showStory(pendingName,Math.min(2,storyStep+1));break;case 'begin-run':if(storyReplay){storyReplay=false;closePanel()}else beginRun(pendingName||read('zs7-name','Player'));break;case 'grenades':if(practice()){game.player.grenades=9;toast('Grenades refilled · practice mode')}break;case 'continue':{const saved=read('zs7-run',null);if(ready&&saved&&game.restore(saved.engine)){run=saved.run;sceneKey='';closePanel()}}break;case 'preview-sound':audio.resume();audio.playMusic('disco');audio.sfx('pickup');setTimeout(()=>{if(paused)audio.pause()},3500);break;case 'install-now':if(installPrompt){await installPrompt.prompt();installPrompt=null;install()}break}});
addEventListener('resize',()=>{lastFit=''});visualViewport?.addEventListener('resize',()=>{lastFit=''});screen.orientation?.addEventListener('change',()=>{lastFit=''});addEventListener('blur',()=>{clearInput();if(game.active&&!panel){pause();menu()}});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();if(game.active&&!panel)menu()}});addEventListener('pagehide',save);addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
applySkin(read('zs7-skin','toxic'));showStart();requestAnimationFrame(frame);renderer.load(fraction=>{const line=$('loadingLine');if(line)line.textContent='Loading game artwork · '+Math.round(fraction*100)+'%'}).then(()=>{ready=true;if(panel==='start'){const b=$('startButton');b.disabled=false;b.textContent='PLAY ZOMBIE SMASH';$('loadingLine').textContent='NO LOGIN · ALL SKINS UNLOCKED'}renderer.draw(game)}).catch(error=>{const line=$('loadingLine');if(line)line.textContent='Artwork download interrupted. Reload to retry.';toast(error.message)});scores.flush();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>navigator.serviceWorker.controller?.postMessage({type:'CACHE_STATUS'})).catch(()=>{});navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='OFFLINE_READY'){write('zs7-offline-ready',true);if($('offlineStatus'))$('offlineStatus').textContent='Game download complete · offline play ready.'}})}
window.ZSInspect=()=>({world:{width:ZSData.W,height:ZSData.H},player:{x:game.player.x,y:game.player.y},wave:game.wave,score:game.score,kills:game.kills,bullets:game.bullets.length,shots:game.shots.length,grenades:game.player.grenades,paused,landscape,scene:game.scene?.kind,scenePhase:game.scene?.phase,boss:game.boss?.bossId,stage:game.boss?.stage,practice:game.practice,active:game.active,over:game.over,panel,ready});
})();
